'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');
const {createCloudClient}=require('../src/cloud-client');const {JsonStore}=require('../src/store');const {buildApp}=require('../server/src/app');const {memoryRepository}=require('../server/src/repository');
test('two desktop clients sync offline edits, retain conflicts and isolate account caches',async t=>{
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'yanji-cloud-test-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));const codes=new Map();const app=buildApp({repository:memoryRepository(),secret:'test-secret-long-enough-to-sign-tokens-12345',deliverCode:async v=>codes.set(v.target,v.code)});t.after(()=>app.close());await app.ready();
 const key=crypto.randomBytes(32);const safeStorage={isEncryptionAvailable:()=>true,encryptString:s=>{const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key,iv);return Buffer.concat([iv,c.getAuthTag?Buffer.alloc(0):Buffer.alloc(0),c.update(s),c.final(),c.getAuthTag()]);},decryptString:b=>{const c=crypto.createDecipheriv('aes-256-gcm',key,b.subarray(0,12));c.setAuthTag(b.subarray(-16));return Buffer.concat([c.update(b.subarray(12,-16)),c.final()]).toString();}};
 let offline=false;
 function device(name){const root=path.join(directory,name);fs.mkdirSync(root);let store=new JsonStore(path.join(root,'local.json'));store.load();const client=createCloudClient({directory:root,safeStorage,getStore:()=>store,activateAccount:async id=>{store=new JsonStore(path.join(root,id||'local','data.json'));store.load();},request:async(url,options)=>{if(offline)throw new Error('offline');const r=await app.inject({url:new URL(url).pathname+new URL(url).search,method:options.method,payload:options.body,headers:options.headers});return {ok:r.statusCode<400,status:r.statusCode,text:async()=>r.body};},backupLocal:async()=>{},importLocal:async()=>{}});return {client,store:()=>store,root};}
 const a=device('a'),b=device('b');for(const d of [a,b])await d.client.configure('http://localhost:3100');await a.client.sendCode({identity:'person@example.com',purpose:'register'});await a.client.register({identity:'person@example.com',password:'Maple4!River',code:codes.get('person@example.com'),agreed:true});await b.client.login({identity:'person@example.com',password:'Maple4!River'});
 a.store().setNotes([{id:'note-test',kind:'daily',dateKey:'2026-09-05',content:'first',title:'笔记',revision:1}]);await a.client.sync();await b.client.sync();assert.equal(b.store().listNotes()[0].content,'first');
 offline=true;b.store().setNotes([{...b.store().listNotes()[0],content:'offline edit'}]);await assert.rejects(b.client.sync(),/offline/);assert.equal(b.store().listNotes()[0].content,'offline edit');offline=false;
 a.store().setNotes([{...a.store().listNotes()[0],content:'other device'}]);await a.client.sync();await b.client.sync();assert.equal(b.client.state().conflicts.length,1);assert.equal(b.store().listNotes()[0].content,'offline edit');await b.client.resolve({entity:'notes',id:'note-test',choice:'local'});await a.client.sync();assert.equal(a.store().listNotes()[0].content,'offline edit');
 await b.client.logout();assert.equal(b.store().listNotes().length,0);assert.equal(b.client.state().user,null);assert.equal(fs.existsSync(path.join(b.root,'cloud-session.enc')),false);
});
