'use strict';

const { contextBridge, ipcRenderer } = require('electron');

const on = (channel) => (callback) => {
  const listener = (_event, ...args) => callback(...args);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
};

contextBridge.exposeInMainWorld('paperTrail', {
  getWorkspace: () => ipcRenderer.invoke('workspace:get'),
  getTodayWidgetData: () => ipcRenderer.invoke('today-widget:get-data'),
  parseSchedule: (input) => ipcRenderer.invoke('schedules:parse', input),
  saveSchedule: (input) => ipcRenderer.invoke('schedules:save', input),
  deleteSchedule: (id) => ipcRenderer.invoke('schedules:delete', id),
  completeSchedule: (id, completed = true) => ipcRenderer.invoke('schedules:complete', id, Boolean(completed)),
  saveCountdown: (input) => ipcRenderer.invoke('countdowns:save', input),
  deleteCountdown: (id) => ipcRenderer.invoke('countdowns:delete', id),
  convertScheduleToTodo: (id, input) => ipcRenderer.invoke('schedules:convert-to-todo', id, input),
  detachSchedule: (id) => ipcRenderer.invoke('schedules:detach', id),
  parseTodo: (input) => ipcRenderer.invoke('todos:parse', input),
  saveTodo: (input) => ipcRenderer.invoke('todos:save', input),
  deleteTodo: (id) => ipcRenderer.invoke('todos:delete', id),
  completeTodo: (id) => ipcRenderer.invoke('todos:complete', id),
  reopenTodo: (id) => ipcRenderer.invoke('todos:reopen', id),
  cancelTodo: (id) => ipcRenderer.invoke('todos:cancel', id),
  snoozeTodo: (id, until) => ipcRenderer.invoke('todos:snooze', id, until),
  getLinkedSchedules: (id) => ipcRenderer.invoke('todos:get-linked-schedules', id),
  scheduleTodo: (id, input) => ipcRenderer.invoke('todos:schedule', id, input),
  createScheduledTodo: (input) => ipcRenderer.invoke('todos:create-scheduled', input),
  convertTodoToSchedule: (id, input) => ipcRenderer.invoke('todos:convert-to-schedule', id, input),
  showScheduleWidget: () => ipcRenderer.invoke('schedule-widget:show'),
  closeScheduleWidget: () => ipcRenderer.invoke('schedule-widget:close'),
  openScheduleWidgetMain: () => ipcRenderer.invoke('schedule-widget:open-main'),
  saveNote: (input) => ipcRenderer.invoke('notes:save', input),
  appendDailyNote: (input) => ipcRenderer.invoke('notes:append-daily', input),
  deleteNote: (id) => ipcRenderer.invoke('notes:delete', id),
  deleteNoteIfEmpty: (id) => ipcRenderer.invoke('notes:delete-if-empty', id),
  addNoteAttachment: (id) => ipcRenderer.invoke('notes:add-attachment', id),
  getNoteAttachment: (id, attachmentId) => ipcRenderer.invoke('notes:get-attachment', id, attachmentId),
  deleteNoteAttachment: (id, attachmentId) => ipcRenderer.invoke('notes:delete-attachment', id, attachmentId),
  openStickyNote: (id) => ipcRenderer.invoke('notes:open-sticky', id),
  getStickyNote: (id) => ipcRenderer.invoke('notes:get-sticky', id),
  createStickyNote: () => ipcRenderer.invoke('notes:create-sticky'),
  saveJobApplication: (input) => ipcRenderer.invoke('jobs:save', input),
  deleteJobApplication: (id) => ipcRenderer.invoke('jobs:delete', id),
  importJobApplications: () => ipcRenderer.invoke('jobs:import'),
  exportJobApplications: () => ipcRenderer.invoke('jobs:export'),
  exportJobApplicationImages: () => ipcRenderer.invoke('jobs:export-image'),
  jobRadar: {
    getSummary: () => ipcRenderer.invoke('job-radar:get-summary'),
    list: (filters) => ipcRenderer.invoke('job-radar:list', filters),
    get: (id) => ipcRenderer.invoke('job-radar:get', id),
    refresh: (request) => ipcRenderer.invoke('job-radar:refresh', request),
    importUrl: (input) => ipcRenderer.invoke('job-radar:import-url', input),
    getProfile: () => ipcRenderer.invoke('job-radar:get-profile'),
    saveProfile: (input) => ipcRenderer.invoke('job-radar:save-profile', input),
    saveSource: (input) => ipcRenderer.invoke('job-radar:save-source', input),
    deleteSource: (id) => ipcRenderer.invoke('job-radar:delete-source', id),
    followCompany: (input) => ipcRenderer.invoke('job-radar:follow-company', input),
    unfollowCompany: (id) => ipcRenderer.invoke('job-radar:unfollow-company', id),
    markSeen: (id) => ipcRenderer.invoke('job-radar:mark-seen', id),
    setHidden: (fingerprint, hidden) => ipcRenderer.invoke('job-radar:set-hidden', fingerprint, hidden),
    addToApplications: (id) => ipcRenderer.invoke('job-radar:add-to-applications', id),
    openSource: (id) => ipcRenderer.invoke('job-radar:open-source', id)
  },
  saveMetadataFields: (fields) => ipcRenderer.invoke('metadata:save-fields', fields),
  clockAttendance: (action) => ipcRenderer.invoke('attendance:clock', action),
  saveAttendance: (input) => ipcRenderer.invoke('attendance:save', input),
  deleteAttendance: (id) => ipcRenderer.invoke('attendance:delete', id),
  getFocusState: () => ipcRenderer.invoke('focus:get-state'),
  startFocus: (input) => ipcRenderer.invoke('focus:start', input),
  stopFocus: () => ipcRenderer.invoke('focus:stop'),
  showCapture: () => ipcRenderer.invoke('capture:show'),
  hideCapture: () => ipcRenderer.invoke('capture:hide'),
  setCaptureContentState: (hasContent) => ipcRenderer.send('capture:content-state', Boolean(hasContent)),
  submitCapture: (input) => ipcRenderer.invoke('capture:submit', input),
  closeSticky: () => ipcRenderer.invoke('sticky:close'),
  setStickyAlwaysOnTop: (enabled) => ipcRenderer.invoke('sticky:set-always-on-top', enabled),
  dismissDeadline: () => ipcRenderer.invoke('deadline:dismiss'),
  snoozeDeadline: (until) => ipcRenderer.invoke('deadline:snooze', until),
  listPapers: () => ipcRenderer.invoke('papers:list'),
  addPaper: (payload) => ipcRenderer.invoke('papers:add', payload),
  refreshPaper: (id) => ipcRenderer.invoke('papers:refresh', id),
  refreshAll: () => ipcRenderer.invoke('papers:refresh-all'),
  markPaperRead: (id) => ipcRenderer.invoke('papers:mark-read', id),
  markAllRead: () => ipcRenderer.invoke('papers:mark-all-read'),
  archivePaper: (id) => ipcRenderer.invoke('papers:archive', id),
  restorePaper: (id) => ipcRenderer.invoke('papers:restore', id),
  linkPaperJourney: (id, targetId) => ipcRenderer.invoke('papers:link-journey', id, targetId),
  unlinkPaperJourney: (id) => ipcRenderer.invoke('papers:unlink-journey', id),
  exportPaper: (id, format) => ipcRenderer.invoke('papers:export', id, format),
  updatePaperDetails: (id, details) => ipcRenderer.invoke('papers:update-details', id, details),
  saveTask: (id, input) => ipcRenderer.invoke('tasks:save', id, input),
  completeTask: (id, taskId, completed) => ipcRenderer.invoke('tasks:complete', id, taskId, completed),
  deleteTask: (id, taskId) => ipcRenderer.invoke('tasks:delete', id, taskId),
  saveRevision: (id, input) => ipcRenderer.invoke('revisions:save', id, input),
  deleteRevision: (id, revisionId) => ipcRenderer.invoke('revisions:delete', id, revisionId),
  removePaper: (id) => ipcRenderer.invoke('papers:remove', id),
  openTrackingPage: (id) => ipcRenderer.invoke('papers:open-tracking', id),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  updateSettings: (patch) => ipcRenderer.invoke('settings:update', patch),
  chooseHomeBannerImage: () => ipcRenderer.invoke('settings:choose-home-banner'),
  refreshBingHomeBanner: () => ipcRenderer.invoke('settings:refresh-bing-banner'),
  chooseDataDirectory: (request) => ipcRenderer.invoke('settings:choose-data-directory', request),
  deleteDataBackups: (confirmed = false) => ipcRenderer.invoke('settings:delete-data-backups', Boolean(confirmed)),
  getUpdateState: () => ipcRenderer.invoke('updates:get-state'),
  checkForUpdates: () => ipcRenderer.invoke('updates:check'),
  downloadUpdate: () => ipcRenderer.invoke('updates:download'),
  installUpdate: () => ipcRenderer.invoke('updates:install'),
  openUpdateReleasePage: () => ipcRenderer.invoke('updates:open-release-page'),
  copyText: (text) => ipcRenderer.invoke('system:copy-text', text),
  openExternal: (url) => ipcRenderer.invoke('system:open-external', url),
  restartApp: () => ipcRenderer.invoke('system:restart-app'),
  setModalWindowState: (active) => ipcRenderer.invoke('window:set-modal-state', Boolean(active)),
  onPapersChanged: on('papers:changed'),
  onRefreshState: on('refresh:state'),
  onUpdateState: on('updates:state'),
  onWorkspaceChanged: on('workspace:changed'),
  onTodayWidgetChanged: on('today-widget:changed'),
  onSettingsChanged: on('settings:changed'),
  onWorkspaceNavigate: on('workspace:navigate'),
  onFocusChanged: on('focus:changed'),
  onCaptureFocus: on('capture:focus'),
  onStickyFocus: on('sticky:focus'),
  onDeadlineShow: on('deadline:show'),
  // Namespaced aliases mirror the v1.1 contract while the flat methods above
  // preserve the existing PaperTrail renderer API.
  todos: {
    parse: (input) => ipcRenderer.invoke('todos:parse', input),
    save: (input) => ipcRenderer.invoke('todos:save', input),
    delete: (id) => ipcRenderer.invoke('todos:delete', id),
    setCompleted: (id, completed = true) => ipcRenderer.invoke(completed ? 'todos:complete' : 'todos:reopen', id),
    setCancelled: (id, cancelled = true) => ipcRenderer.invoke(cancelled ? 'todos:cancel' : 'todos:reopen', id),
    schedule: (id, input) => ipcRenderer.invoke('todos:schedule', id, input),
    convertToSchedule: (id, input) => ipcRenderer.invoke('todos:convert-to-schedule', id, input),
    getLinkedSchedules: (id) => ipcRenderer.invoke('todos:get-linked-schedules', id)
  },
  schedules: {
    convertToTodo: (id, input) => ipcRenderer.invoke('schedules:convert-to-todo', id, input)
  }
});
