'use strict';
const applicationCompanies=new Map();
let companyRefreshTimer;
async function refreshApplicationCompanies(){
  if(!workbenchApi.listCompanies)return;
  try{for(const company of await workbenchApi.listCompanies())applicationCompanies.set(company.id,company);for(const node of document.querySelectorAll('[data-company-logo]')){const company=applicationCompanies.get(node.dataset.companyLogo);if(company)node.innerHTML=companyLogoInner(company,company.name);}}catch{ /* Company images never block the application list. */ }
}
const changedCompanyIds=new Set();
workbenchApi.onCompanyChanged?.(id=>{changedCompanyIds.add(id);clearTimeout(companyRefreshTimer);companyRefreshTimer=setTimeout(async()=>{for(const key of [...changedCompanyIds]){changedCompanyIds.delete(key);try{const company=await workbenchApi.getCompany(key);applicationCompanies.set(key,company);for(const node of document.querySelectorAll('[data-company-logo]'))if(node.dataset.companyLogo===key)node.innerHTML=companyLogoInner(company,company.name);}catch{}}},100);});
function companyLogoInner(company,name){return company?.logoData&&/^data:image\/png;base64,/.test(company.logoData)?`<img src="${company.logoData}" alt="">`:`<span>${wbEscape(company?.shortName||Array.from(name||'企')[0])}</span>`;}
function companyLogo(job){const company=applicationCompanies.get(job.companyId);return `<span class="company-logo" data-company-logo="${wbEscape(job.companyId||'')}" data-company-name="${wbEscape(job.company)}" aria-label="${wbEscape(job.company)} Logo">${companyLogoInner(company,job.company)}</span>`;}
document.addEventListener('error',event=>{const box=event.target.closest?.('[data-company-logo]');if(box&&event.target.tagName==='IMG')box.innerHTML=companyLogoInner(null,box.dataset.companyName);},true);
function applicationTagColor(tag){const hash=Array.from(tag).reduce((h,char)=>Math.imul(h^char.codePointAt(0),16777619)>>>0,2166136261);return (hash^(hash>>>16))&7;}
function applicationTags(job){const tags=[...new Set((job.tags||[]).flatMap(t=>String(t).split(/[;；]/)).map(t=>t.trim()).filter(Boolean))];return tags.length?`<div class="application-tags">${tags.slice(0,3).map(t=>`<span data-tag-color="${applicationTagColor(t)}" title="${wbEscape(t)}">${wbEscape(t)}</span>`).join('')}${tags.length>3?`<span title="${wbEscape(tags.slice(3).join(' · '))}">+${tags.length-3}</span>`:''}</div>`:'';}
function applicationStage(job){const D=window.YanjiCareerData,current=job.status==='closed'?job.closureReason||'rejected':'stage:'+job.workflow.currentStageId;const options=(job.workflow?.stages||[]).map(s=>['stage:'+s.id,s.name]);if(!options.some(([id,label])=>/AI\s*面/i.test(label))){const pos=options.findIndex(([id,label])=>/测评|笔试|网测/.test(label));options.splice(pos>=0?pos:1,0,['stage:stage-ai-interview','AI 面']);}options.push(['rejected','被拒绝'],['withdrawn','已放弃']);if(D.category(D.current(job)?.name||'')==='offer')options.push(['offer-declined','Offer 已拒绝']);return `<select class="application-stage${job.status==='closed'?' ended':''}" data-application-stage-select="${wbEscape(job.id)}" aria-label="${wbEscape(job.company)}当前阶段">${options.map(([value,label])=>`<option value="${wbEscape(value)}"${value===current?' selected':''}>${wbEscape(label)}</option>`).join('')}</select>`;}
 document.addEventListener('change',async event=>{const select=event.target.closest('[data-application-stage-select]');if(!select)return;const value=select.value;select.disabled=true;const ok=await saveCareerPatch(select.dataset.applicationStageSelect,j=>{const D=window.YanjiCareerData;if(value==='stage:stage-ai-interview'&&!j.workflow.stages.some(s=>s.id==='stage-ai-interview')){j=structuredClone(j);const pos=j.workflow.stages.findIndex(s=>/测评|笔试|网测/.test(s.name));j.workflow.stages.splice(pos>=0?pos:1,0,{id:'stage-ai-interview',name:'AI 面'});}if(value.startsWith('stage:'))return D.advance(j.status==='closed'?D.transition(j,'reopened'):j,value.slice(6));return D.transition(j,value);});if(!ok)renderJobs();});
function applicationProgress(job){const workflow=clientJobWorkflow(job.workflow),index=workflow.stages.findIndex(s=>s.id===workflow.currentStageId);return `<div class="application-progress" aria-label="招聘进度">${workflow.stages.map((s,i)=>{const date=workflow.timeline.find(t=>t.stageId===s.id)?.date;const stopped=job.status==='closed'&&i===index;return `<button type="button" data-application-history="${wbEscape(job.id)}" data-stage-color="${i}" data-stage-name="${wbEscape(s.name)}" class="${stopped?'stopped':i<=index?'reached':''}" title="${wbEscape(s.name)}${date?' · '+applicationDate(date):''}${stopped?' · '+wbEscape(window.YanjiCareerData.outcomeLabel(job)):''}" aria-label="${wbEscape(s.name)}${stopped?' 已终止':''}">${stopped?'×':'●'}</button>`;}).join('')}</div>`;}
function applicationDate(date){return jobDateLabel(date,{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'});}
function applicationTimeButton(job,kind,value,label){const remaining=value?Date.parse(value)-Date.now():Infinity,tone=job.status!=='closed'&&remaining<=7*86400000?(remaining<0?' overdue':remaining<=3*86400000?' urgent':' soon'):'';return `<button type="button" class="application-time${tone}" data-application-time="${wbEscape(job.id)}" data-time-kind="${kind}" aria-label="修改${label}"><span>${label}</span><time>${value?wbEscape(applicationDate(value)):'—'}</time></button>`;}
function applicationTimes(job){const info=window.YanjiCareerData.deadline(job);return [{kind:'stage-deadline',date:info.value,label:info.label,urgent:job.status!=='closed'&&info.value&&Date.parse(info.value)-Date.now()<=7*86400000}];}
function applicationActions(job){const id=wbEscape(job.id);return `<button type="button" class="career-tool application-edit" data-edit-job="${id}">编辑</button><button type="button" class="career-tool application-edit" data-application-logo="${id}" aria-label="设置公司 Logo">Logo</button>${job.sourceUrl?`<button type="button" class="career-tool" data-open-job-source="${wbEscape(job.sourceUrl)}" aria-label="岗位链接">${careerIcon('link')}</button>`:''}<button type="button" class="career-tool application-more" data-application-menu="${id}" aria-label="更多操作">···</button>${job.status!=='closed'?`<button type="button" class="career-tool application-reject" data-application-reject="${id}" aria-label="标记被拒绝" title="标记被拒绝"><svg class="career-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="m8 8 8 8m0-8-8 8"/></svg></button>`:''}`;}
function applicationDialog(title,html){let dialog=document.getElementById('applicationActionDialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='applicationActionDialog';document.body.append(dialog);dialog.addEventListener('pointerdown',e=>{dialog.dataset.backdrop=String(e.target===dialog);});dialog.addEventListener('click',e=>{if(e.target===dialog&&dialog.dataset.backdrop==='true')dialog.close();});}dialog.innerHTML=`<header><h2>${wbEscape(title)}</h2><button type="button" class="career-tool" data-application-close aria-label="关闭">×</button></header>${html}<p class="form-error" role="alert"></p>`;dialog.querySelector('[data-application-close]').onclick=()=>dialog.close();if(!dialog.open)dialog.showModal();return dialog;}
function applicationMenu(job){const id=wbEscape(job.id);const dialog=applicationDialog(job.company+' · '+job.role,`<div class="application-menu"><button data-menu-action="edit">编辑岗位</button><button data-menu-action="stage">更新阶段 / 投递结果</button><button data-menu-action="history">查看完整历史</button>${job.status==='closed'?'<button data-menu-action="reopened">恢复进行中</button>':'<button data-menu-action="withdrawn">已放弃 / 归档</button>'}<button class="danger" data-menu-action="delete">删除岗位</button></div>`);dialog.querySelectorAll('[data-menu-action]').forEach(button=>button.onclick=async()=>{const action=button.dataset.menuAction;if(action==='edit'){dialog.close();openJobEditor(job);}else if(action==='stage')applicationStageDialog(job);else if(action==='history')applicationHistory(job);else if(action==='delete'){dialog.close();deleteJobById(job.id);}else{button.disabled=true;const ok=await saveCareerPatch(job.id,j=>window.YanjiCareerData.transition(j,action));if(ok)dialog.close();else button.disabled=false;}});}
function applicationStageDialog(job){const D=window.YanjiCareerData;const dialog=applicationDialog('更新投递进度',`<form class="application-stage-form"><p>${wbEscape(job.company)} · ${wbEscape(job.role)}</p><label>阶段或结果<select name="stage">${job.status==='closed'?'<option value="reopened">恢复进行中（保留原阶段）</option>':(job.workflow?.stages||[]).map(s=>`<option value="stage:${wbEscape(s.id)}"${s.id===job.workflow.currentStageId?' selected':''}>${wbEscape(s.name)}</option>`).join('')}<option value="rejected">被拒绝</option><option value="withdrawn">已放弃</option>${D.category(D.current(job)?.name||'')==='offer'?'<option value="offer-declined">Offer 已拒绝</option>':''}</select></label><p class="application-help">保留此前阶段和时间，记录本次更新。</p><button type="submit" class="button primary">保存状态</button></form>`);dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=dialog.querySelector('[type="submit"]');button.disabled=true;const value=dialog.querySelector('select').value;const ok=await saveCareerPatch(job.id,j=>value.startsWith('stage:')?D.advance(j,value.slice(6)):D.transition(j,value));if(ok)dialog.close();else button.disabled=false;};}
function applicationHistory(job){const D=window.YanjiCareerData;const items=(job.workflow?.timeline||[]).map(t=>({date:t.date,label:job.workflow.stages.find(s=>s.id===t.stageId)?.name||'历史阶段'}));for(const h of job.stageHistory||[])items.push({date:h.occurredAt,label:({advanced:'推进阶段',rejected:'被拒绝',withdrawn:'已放弃','offer-declined':'Offer 已拒绝',reopened:'恢复进行中'}[h.action]||h.action)+' · '+h.stageName});items.sort((a,b)=>Date.parse(a.date)-Date.parse(b.date));applicationDialog('投递历史',`<p>${wbEscape(job.company)} · ${wbEscape(D.outcomeLabel(job))}</p><ol class="application-history">${items.map(x=>`<li><strong>${wbEscape(x.label)}</strong><time>${applicationDate(x.date)}</time></li>`).join('')||'<li>尚未添加阶段时间</li>'}</ol>`);}
async function applicationLogoDialog(job){await refreshApplicationCompanies();const company=applicationCompanies.get(job.companyId);if(!company){showWorkbenchToast('公司资料正在载入，请稍后重试','error');return;}const dialog=applicationDialog('公司 Logo',`<form class="application-logo-form"><p>${wbEscape(company.name)} · 同公司岗位共享</p><div class="application-logo-preview">${companyLogo(job)}<span data-logo-status>${wbEscape(company.logoRemoteUrl?'图标地址：'+company.logoRemoteUrl:company.logoSource==='manual'?'使用手动上传的图片':company.logoError||'填写官网后获取图标，也可直接选择图片')}</span></div><label>公司官网或图标链接<input name="website" type="text" value="${wbEscape(company.website||'')}" placeholder="如 www.sangfor.com.cn 或完整图片链接"></label><label>简称（图片不可用时显示）<input name="shortName" maxlength="12" value="${wbEscape(company.shortName||'')}"></label><div class="application-logo-actions"><button type="button" data-logo-manual>选择图片</button><button type="button" data-logo-refresh>刷新 Logo</button><button type="submit" class="button primary">保存</button></div></form>`);const run=async fn=>{try{await fn();await refreshApplicationCompanies();const latest=applicationCompanies.get(company.id);dialog.querySelector('[data-logo-status]').textContent=latest.logoRemoteUrl?'图标地址：'+latest.logoRemoteUrl:latest.logoSource==='manual'?'使用手动上传的图片':latest.logoStatus==='pending'?'正在获取网站图标…':latest.logoError||'未获取到可用图标，可手动选择图片';dialog.querySelector('.form-error').textContent=latest.logoError||'';}catch(e){dialog.querySelector('.form-error').textContent=e.message;}};dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const button=dialog.querySelector('[type="submit"]');button.disabled=true;try{await workbenchApi.configureCompany(company.id,{website:dialog.querySelector('[name="website"]').value,shortName:dialog.querySelector('[name="shortName"]').value});dialog.close();await refreshApplicationCompanies();}catch(error){dialog.querySelector('.form-error').textContent=error.message;button.disabled=false;}};dialog.querySelector('[data-logo-manual]').onclick=()=>run(()=>workbenchApi.setCompanyLogo(company.id));dialog.querySelector('[data-logo-refresh]').onclick=()=>run(async()=>{await workbenchApi.configureCompany(company.id,{website:dialog.querySelector('[name="website"]').value,shortName:dialog.querySelector('[name="shortName"]').value});await workbenchApi.refreshCompanyLogo(company.id);});}
function applicationTimeDialog(job,kind){if(kind==='stage-deadline'){applicationDeadlineDialog(job);return;}const D=window.YanjiCareerData;const info=kind.startsWith('stage:')?{value:job.workflow.timeline.find(t=>t.stageId===kind.slice(6))?.date,label:job.workflow.stages.find(t=>t.id===kind.slice(6))?.name||'阶段时间'}:kind==='applied'?{value:D.applied(job),label:'投递时间'}:kind==='deadline'?{value:job.deadline,label:'截止时间'}:kind==='next'?{value:job.nextFollowUpAt,label:'下次跟进'}:D.time(job);const date=new Date(info.value),value=info.value&&Number.isFinite(date.getTime())?new Date(date.getTime()-date.getTimezoneOffset()*60000).toISOString().slice(0,16):'';const dialog=applicationDialog(info.label,`<form><label>${wbEscape(job.company)}<input type="datetime-local" name="time" value="${value}"></label><button type="submit" class="button primary">保存时间</button></form>`);dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const v=dialog.querySelector('input').value,iso=v?new Date(v).toISOString():null;const ok=await saveCareerPatch(job.id,j=>{if(kind.startsWith('stage:')){const workflow=structuredClone(j.workflow),stageId=kind.slice(6);workflow.timeline=workflow.timeline.filter(t=>t.stageId!==stageId);if(iso)workflow.timeline.push({stageId,date:iso});return {workflow};}if(kind==='next')return {nextFollowUpAt:iso,nextActionAt:iso};if(kind==='deadline')return {deadline:iso};if(kind==='applied'){const workflow=structuredClone(j.workflow),stage=workflow.stages.find(s=>D.category(s.name)==='apply');if(stage){workflow.timeline=workflow.timeline.filter(t=>t.stageId!==stage.id);if(iso)workflow.timeline.push({stageId:stage.id,date:iso});}return {appliedAt:iso,workflow};}return D.withTime(j,iso);});if(ok)dialog.close();};}
document.addEventListener('click',event=>{const target=event.target.closest('[data-application-menu],[data-application-stage],[data-application-history],[data-application-time]');if(!target)return;const id=target.dataset.applicationMenu||target.dataset.applicationStage||target.dataset.applicationHistory||target.dataset.applicationTime,job=wb.workspace.jobApplications.find(j=>j.id===id);if(!job)return;if(target.dataset.applicationMenu)applicationMenu(job);else if(target.dataset.applicationStage)applicationStageDialog(job);else if(target.dataset.applicationHistory)applicationHistory(job);else applicationTimeDialog(job,target.dataset.timeKind);});

refreshApplicationCompanies();

function applicationDeadlineDialog(job){
 const D=window.YanjiCareerData,P=window.YanjiDeadlineParser,info=D.deadline(job),base=new Date(),original=P.localValue(info.value);
 const dialog=applicationDialog(info.label,`<form class="application-deadline-form"><p>${wbEscape(job.company)} · ${wbEscape(job.role)}</p><label>输入截止时间<input name="deadlineText" type="text" value="${wbEscape(original)}" placeholder="2026-09-12 18:00 / 明天下午5点 / 72小时 / 72小时内" autocomplete="off"></label><label>或选择日期和时间<input name="deadlinePicker" type="datetime-local" value="${original.replace(' ','T')}"></label><p class="application-help">相对时间从 ${wbEscape(P.localValue(base))} 起算；只更新“${wbEscape(info.label)}”。</p><output class="application-deadline-preview" aria-live="polite"></output><footer><button type="button" data-deadline-clear class="button secondary">清除</button><button type="submit" class="button primary">保存截止时间</button></footer></form>`);
 const text=dialog.querySelector('[name="deadlineText"]'),picker=dialog.querySelector('[name="deadlinePicker"]'),preview=dialog.querySelector('output'),button=dialog.querySelector('[type="submit"]');
 const parsed=()=>text.value===original?{valid:true,value:info.value,label:info.value?P.localValue(info.value):'清除当前阶段截止时间'}:P.parse(text.value,base);
 const show=()=>{const result=parsed();preview.textContent=result.valid?(result.value?'截止于 '+result.label:result.label):result.error;button.disabled=!result.valid;return result;};
 text.oninput=()=>{const value=show();picker.value=value.valid&&value.value?P.localValue(value.value).replace(' ','T'):'';};picker.oninput=()=>{text.value=picker.value.replace('T',' ');show();};
 dialog.querySelector('[data-deadline-clear]').onclick=()=>{text.value='';picker.value='';show();};
 dialog.querySelector('form').onsubmit=async e=>{e.preventDefault();const result=show();if(!result.valid)return;button.disabled=true;const current=wb.workspace.jobApplications.find(j=>j.id===job.id);if(D.deadline(current).stageId!==info.stageId){dialog.querySelector('.form-error').textContent='岗位阶段已变化，请重新打开截止时间。';button.disabled=false;return;}const ok=await saveCareerPatch(job.id,j=>D.withDeadline(j,result.value));if(ok)dialog.close();else button.disabled=false;};show();
}

document.addEventListener('click',event=>{const button=event.target.closest('[data-application-logo]');if(!button)return;const job=wb.workspace.jobApplications.find(j=>j.id===button.dataset.applicationLogo);if(job)applicationLogoDialog(job);});

document.addEventListener('click',async event=>{const button=event.target.closest('[data-application-reject]');if(!button)return;button.disabled=true;const ok=await saveCareerPatch(button.dataset.applicationReject,j=>window.YanjiCareerData.transition(j,'rejected'));if(!ok)button.disabled=false;});
